### PR TITLE
Allow firestore-counter to run on the emulator

### PR DESCRIPTION
**Pull request by KenCorbettJr**
When running firestore-counter locally and the counter is first starting there are not always workers in the controllerData.  This update prevents an error in this case and allows the counter to start and function normally.

This is the error I was getting:

Screen Shot 2022-08-08 at 4 37 34 PM

After this update, I no longer get this error.

### CODE REVIEW

**Review by dackers86 — APPROVED** [review]

**Comment by KenCorbettJr** [comment]
Ahh yes.  I see.  I fixed it to do the check again but without option chaining.

**Comment by KenCorbettJr** [comment]
@dackers86 could you approve this pull request again?

**Comment by KenCorbettJr** [comment]
What do I need to get this merged? It looks like I still need approval from @dackers86 but I already got approval.

**Comment by pavelgj** [comment]
I changed the base of this PR -- all new changes need to go into `next`.

**Comment by dackers86** [comment]
Hi @KenCorbettJr 

Apologies for the delay on this one, there are some conflicts and files changed unrelated to the PR. 

We are currently looking into adding a better testing environment for this Extension. 

We'll look to patch up and add this PR with the testing environment for the next release.

**Review by dackers86 — APPROVED** [review]

**Pull request merged**
