### PR TITLE
Clarifying docs for non-interactive use of `fs-bq-import-collection`

### PR DESCRIPTION
**Pull request by gregfenton**
To resolve https://github.com/firebase/extensions/issues/545

### CODE REVIEW

**Comment by jhuleatt** [comment]
Thanks @gregfenton! This makes sense to me.  Assigning @kevinthecheung for a doc review, after which we can merge.

**Review by kevinthecheung — APPROVED** [review]

**Comment by jhuleatt** [comment]
@gregfenton looks like it's failing our formatting check. Can you please run `npm run format` from the repository root to fix it?

**Comment by gregfenton** [comment]
I wasn't aware that I should run `npm run lint`.  Is there a developer guide/doc that outlines the proper way to update a *.md file and contribute to this project properly?

(My initial contribution was simply from editing the README via the GitHub web UI...and that clearly wasn't successful 😕 )

With this failure, I do not see any type of error message to indicate *what* to investigate next.

Sorry for the bother.  I probably owe the team a beer or something?

**Comment by russellwheatley** [comment]
Hey @gregfenton, thanks for the PR. Do you mind resolving the merge conflict and also removing the re-compiled `firestore-translate-text` files? Thanks.

**Comment by gregfenton** [comment]
> Do you mind resolving the merge conflict and also removing the re-compiled `firestore-translate-text` files? Thanks.

@russellwheatley - conflict resolved.  Not sure which are the "re-compiled `firestore-translate-text` files"?  I believe this PR only includes an update to 2 files ("Files changed" tab in GitHub), but I could be mistaken.  As mentioned in this conversation, I'm unaware of the actual steps beyond "change the docs/code" to follow.  Is there a Dev Guide or something for direction? I don't like being a burden or wasting y'all's time.

**Comment by russellwheatley** [comment]
@gregfenton Thanks for the quick response! It appears the merge resolved those files.  I'm sorry to say we don't have a dev guide currently, but I can ask the question about getting one added to the repo 😄

**Review by russellwheatley — APPROVED** [review]

**Review by jhuleatt — APPROVED** [review]

**Pull request merged**
