### PR TITLE
feat(*): add Taiwan and Singapore Cloud Function Locations

### PR DESCRIPTION
**Pull request by dackers86**
Separating PR https://github.com/firebase/extensions/pull/720

### CODE REVIEW

**Comment by dackers86** [comment]
Testing

image

image

**Review by russellwheatley — APPROVED** [review]
LGTM

**Review by bluet — APPROVED** [review]
LGTM

**Comment by bluet** [comment]
@russellwheatley @dackers86 will this be merged anytime soon?

We're using a forked version of image resize extension just for fixing this, and would really like to come back to use this repo once this PR gets merged. :sweat_smile:

**Pull request merged**
