### PR TITLE
November 7, 2019 Release

### PR DESCRIPTION
**Pull request by laurenzlong**

### CODE REVIEW

**Comment by rosariopfernandes** [comment]
@googlebot I consent.

**Comment by laurenzlong** [comment]
Thanks @rosariopfernandes ! Unfortunately, we will be delaying the release by a week since we've discovered a bug with updating extensions.

**Comment by andreimateiro** [comment]
Any updates here? It was targeted for 31 Oct

**Comment by laurenzlong** [comment]
@andreimateiro Thanks for the question! Unfortunately we've had to delay the release again, it is now slated for this Thurs.

**Comment by laurenzlong** [comment]
@googlebot rescan

**Comment by Salakar** [comment]
@googlebot I consent.

**Pull request merged**
