### PR TITLE
[storage-resize-images] Update to v0.1.1

### PR DESCRIPTION
**Pull request by laurenzlong**
Format of changelog will probably change in the future (since we may be automating the generation of it). But this is just something to have for now.

### CODE REVIEW

**Comment by rafikhan** [comment]
LGTM

**Comment by karayu** [comment]
LGTM; Let's not forget to create a release in GitHub when this goes out

**Comment by laurenzlong** [comment]
No. We should probably just remove the version number in package.jsons for all the extensions. It's only the version number in extension.yaml that counts, and it's just upkeep to try to keep the two in sync, and confusion when they're out of sync.

**Comment by bkendall** [comment]
That's not a horrible idea, in all honesty. These will never be published via `npm`, so it shouldn't break anything to remove them

**Pull request merged**
