### PR TITLE
feat(firestore-bigquery-export): bring back backfill

### LINKED ISSUE #1890: 🐛 [firestore-bigquery-export] No option for importing old data when setting up extention
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firebase/firestore-bigquery-export@0.1.43
- Extension version: 0.1.43
- Configuration values (redact info where appropriate):
Happens with default configuration

### [REQUIRED] Step 3: Describe the problem
There is no 
option to import existing documents when setting up the extention

Screenshot 2023-12-21 110738
Screenshot 2023-12-21 110752

#### Steps to reproduce:

go to the extensions page in firebase console, install the bigquery extension

##### Expected result
To see be asked to import old data

##### Actual result
No option to import old data

### PR DESCRIPTION
**Pull request by jauntybrain**
Brings back the backfill feature and updates related docs.

Closes #1890

### CODE REVIEW

**Review by pr-Mais — APPROVED** [review]

**Comment by pr-Mais** [comment]
Can we link the related issues

**Comment by pr-Mais** [comment]
can we add some notes in the POSTINSTALL about not using the import script if DO_BACKFILL is true? probably a whole section with all things to consider upon importing.

**Comment by pr-Mais** [comment]
@jauntybrain check the conflicts, from my last formatting PR

**Comment by paward35** [comment]
@pr-Mais @jauntybrain thanks for bringing this back! Do you know when this will be released? Is it possible to use this pre release ?

**Comment by cabljac** [comment]
hi @paward35, after investigation, the backfill strategy still wasn't suitable, and so was not included. For now, the only solutions are to use the import script provided in this repo, or to set up some kind of custom solution (e.g a Dataflow job)

**Pull request merged**
