### PR TITLE
fix(firestore-bigquery-export): add failurePolicy. #1060

### PR DESCRIPTION
**Pull request by ytetsuro**
Some data is not in BigQuery.
Functions now retries when there is an error.

### CODE REVIEW

**Review by dackers86 — APPROVED** [review]

**Comment by dackers86** [comment]
Hi @ytetsuro

Thanks for the PR, could you sign the CLA as detailed above. We will look to get this merged into a future release.

**Comment by ytetsuro** [comment]
Thanks for the fixed lint error.
I signed CLA.

Please review.

**Comment by ytetsuro** [comment]
@dackers86 

Am I worth rebasing this?

**Comment by dackers86** [comment]
Yes, you can leave this with us. I'll merge this in with the latest branch!

**Pull request merged**
