### PR TITLE
fix(firestore-bigquery-export): remove multiple database support

### PR DESCRIPTION
**Pull request by cabljac**
should fix https://github.com/firebase/extensions/issues/2090

### CODE REVIEW

**Comment by jggomezt** [comment]
When will you be supporting multi-db??

**Comment by marcuscorreasmash** [comment]
i need too supporting multi-db :(

**Comment by IM-CrazyDeveloper** [comment]
any chance to get fix or workaround to support multi DB?

**Comment by rummanext** [comment]
1+ here

**Comment by beyondprompting** [comment]
still waiting for this, is so basic to use the extension

**Comment by calebripley** [comment]
Would love to use this extension as well but can't due to my data not being in default. Would also recommend updating the docs to be explicit that default db will be used.

**Comment by cabljac** [comment]
I will escalate this to the team, we're blocked from a platform side at the moment, as v1 functions dont support non-default db, and extensions don't support v2 for firestore triggers.

**Pull request merged**
