### PR TITLE
fix(storage-resize-images): fix bug where name of resized file was missing original name if there was no file extension

### PR DESCRIPTION
**Pull request by yuichkun**
I'm not sure if it is the expected behavior or not, and if so, please disregard this PR.

## Issue
As someone has pointed out in [this comment](https://github.com/firebase/extensions/issues/130#issuecomment-564425978), when a user uploads an image to the storage with a ref name **without** an extension, resized image's name gets to be trimmed like `_200x200`.

Below is a sample code that reproduces this.

```typescript
const storageRef = firebase.storage().ref('RANDOM_PATH')
const folderRef = storageRef.child('my_beautiful_cat')
await folderRef.put(e.target.files[0]) // got this from File API
```

Screenshot 2019-12-13 02 44 02

## Root Cause

It seems like the problem is happening where it [extracts the file name without extension](https://github.com/firebase/extensions/blob/next/storage-resize-images/functions/src/index.ts#L66). 
The current implementation is based on the premise that the ref would always have an extension, in other words, `fileExtension.length` is never 0. But, as it is not a restriction that firebase SDK enforces, when the file ref does not contain an extension, it should simply use the ref name, I guess.

## Fix

Node.js's `path.basename` can extract filename without extension.

reference: https://nodejs.org/docs/latest-v8.x/api/path.html#path_path_basename_path_ext

### CODE REVIEW

**Comment by yuichkun** [comment]
#135

**Comment by Ehesp** [comment]
Currently, if a user uploads an image called `image.jpg`, it would get resized to say `image_200x200.jpg`, as expected.

With this change, although it would correctly handle images without an extension, wouldn't it always output an image with no extension name, which is different than the current implementation? For example:

`image.jpg` -> `image_200x200.jpg`
vs
`image.jpg` -> `image_200x200`

My thinking is if the user uploads an image with an extension, we should persist it when resizing, if not we don't add it. What do you think?

**Comment by Ehesp** [comment]
Also I think issue #130 is unrelated to this.

**Comment by yuichkun** [comment]
Hi @Ehesp , thank you for your review.

`My thinking is if the user uploads an image with an extension, we should persist it when resizing, if not we don't add it.`  
I completely agree with you, and I believe this PR does abide by that!

As far as I understand, `fileNameWithoutExtension`, which literally refers to the file name **without** an extension,  is passed on to the `resizeImage` function along with `fileExtension`.

https://github.com/firebase/extensions/blob/947d533eb4531dc311b10f8a94e1c60fde9e12cc/storage-resize-images/functions/src/index.ts#L92-L105

The `resizeImage` function then reconstructs the output file name like below,

https://github.com/firebase/extensions/blob/947d533eb4531dc311b10f8a94e1c60fde9e12cc/storage-resize-images/functions/src/index.ts#L158

So, when the image does not have a file extension, in other words `fileExtension` is `''`,  `resizedFileName` does **not** have a file extension but the **original file name** with **size suffix**, and when the image does have a file extension, it **preserves** the file extension.

I haven't written unit tests for above since it kind of exceeds the scope of this topic, but if it's desirable, I guess I can provide one. 

Btw, are there anyways I can actually use my local version of this extension with an actual Firebase project? I couldn't find a way to confirm that everything works in harmony 🤔

**Comment by yuichkun** [comment]
Also, my apologies for mentioning an unrelated issue! Edited the description.

**Comment by Ehesp** [comment]
Ah yes you are correct, thanks for explaining. I also didn't realise that a `.slice` with a `-0` value totally removes the string (`"foo".slice(0, -0)` = `""`).

Let me give it a go and I'll get back to you.

**Comment by Ehesp** [comment]
Tested this out and it's working:

image

Funnily enough, I added an image through gsutil & then realised I hit issue #130. So although this works, https://github.com/firebase/extensions/pull/142 needs merging too :)

**Pull request merged**
