### PR TITLE
feat(firestore-bigquery-export) Add us-central-1 as a dataset location option

### PR DESCRIPTION
**Pull request by dackers86**
fixes: https://github.com/firebase/extensions/issues/602

### CODE REVIEW

**Comment by dackers86** [comment]
## Testing

image

**Review by Ehesp — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]

**Review by Salakar — APPROVED** [review]

**Comment by jhuleatt** [comment]
@firebase/invertase can you please try this new region out and post some screenshots? Just want to be 100% sure this region works.

**Comment by dackers86** [comment]
@jhuleatt 

Screenshot of created dataset

image

Example screenshot of data synced with Firestore

image

**Comment by jhuleatt** [comment]
Thanks @dackers86 🚀

**Pull request merged**
