### PR TITLE
feat(firestore-bigquery-export): support cross-project import with the import script

### PR DESCRIPTION
**Pull request by cabljac**
This is to replace the PR [here](https://github.com/firebase/extensions/pull/1687) as refactors have made the original fork diverge too much from `next`. Need to re-review before we merge.

Should fix https://github.com/firebase/extensions/issues/1688

### CODE REVIEW

**Comment by jwerner08** [comment]
Hey @cabljac, Just wanted to share my thanks and appreciation for helping out here! :)

**Comment by janssen92** [comment]
You could use the PROJECT_ID as a fallback if no big query project id is provided to be downward compatible

**Comment by Naihell** [comment]
Hey there! Any news about this one? I've tested using 0.1.43 extension version, following @jwerner08's instructions, but for some reason BigQuery project Id was always being setted to "undefined". On the other way, if I manually overwrite project variables, everything runs perfectly.

Having this functionality in a production branch would be amazing, it's quite easy to use and most of my jobs runs on cross projects.

Thanks for the excellent work!

**Comment by pr-Mais** [comment]
@jauntybrain can you resolve the conflict

**Review by pr-Mais — APPROVED** [review]

**Pull request merged**
