### PR TITLE
Brandfolder proposal/extensions/firestore biquery import script

### PR DESCRIPTION
**Pull request by jwerner08**
Hello! 

I was working through your extension, and when I came to the backfill script, I didn't see any place to update the GCP project id used for BigQuery, which is a configurable parameter when installing the extension via firebase (as seen by parameter `Project Id`). 

This pr adds the functionality to specify a BigQuery instance located within a separate GCP project from the Firebase instance. I'm by no means a pro at typescript (I work primarily in python), and mostly pattern matched to add this functionality, so if there's any issues with the code feel free to edit. I have tested that this works successfully for me though. 

Thanks!

### CODE REVIEW

**Comment by cabljac** [comment]
I will need to test it out before we release it but lgtm!

**Comment by jwerner08** [comment]
@cabljac Feel free to look at the [issues thread here](https://github.com/firebase/extensions/issues/1688), as it seems the solution I submitted could be made more robust?

**Comment by dackers86** [comment]
Hey! @jwerner08 This PR looks great, apologies for the delay.

As a lot of refactoring has been added since this PR, we have a few options:

1. Could you resolve the conflicts.
2. Create a fresh PR and re-add the updates to ensure that you retain credit for this fix.
3. Alternatively, i'm happy to do this and add you as a co-collaborator.

Let me know what you think. Thanks!

**Comment by jwerner08** [comment]
@dackers86
Hey!

I've completed a rebase of my branch to incorporate the latest changes from next. Before doing so I also added [this commit](https://github.com/firebase/extensions/pull/1687/commits/8b0a45d9744c0f4a268bc59989c2d0cb77274f92), which was necessary to ensure non-interactive CLI execution works correctly. I didn't encounter any conflicts during my rebase, which leaves me a bit puzzled about that discrepancy. I've double-checked and made sure that my local branch is fully up-to-date with `next`.

If it simplifies matters, I'm definitely willing to create a new pull request, else I hope the "This branch has conflicts that must be resolved" is just a false positive?

Thanks!

**Comment by cabljac** [comment]
Hey, the import script had some refactoring done recently and this is probably most of the conflicts. I'm going to try and make sense of things and resolve them, i've opened a PR to track this -  https://github.com/firebase/extensions/pull/1799/files

**Comment by cabljac** [comment]
I think your fork is quite far behind `next`

**Comment by cabljac** [comment]
Today I will replay your commits on the latest next and make sure it's attributed correctly, with you as main author

**Comment by cabljac** [comment]
closing in favour of https://github.com/firebase/extensions/pull/1800 for now

**Pull request closed without merging**
