### PR TITLE
feat(firestore-bigquery-export): stringified_map schema type for gen-schema-view script

### PR DESCRIPTION
**Pull request by dackers86**
Added a new `stringified_map` schema type. This allows properties (i.e maps) to be stringified into the specified column.

### CODE REVIEW

**Comment by dackers86** [comment]
Initial PR created. Test coverage is still needed for the new schema type.

**Comment by russellwheatley** [comment]
@googlebot I consent.

**Comment by russellwheatley** [comment]
fixes #292 & #408.

**Comment by russellwheatley** [comment]
Shows the `stringified_map` type as a column in a BigQuery view:
Screenshot 2020-12-21 at 15 53 16

**Review by Salakar — APPROVED** [review]

**Comment by gregfenton** [comment]
Are there any docs for this new capability?  How does one take advantage of it?

**Comment by russellwheatley** [comment]
Here's the PR for the documentation update https://github.com/firebase/extensions/pull/567

**Pull request merged**
