### PR TITLE
chore: remove study - date has passed

### PR DESCRIPTION
**Pull request by brucearctor**

### CODE REVIEW

**Comment by brucearctor** [comment]
@i14h

**Comment by brucearctor** [comment]
@i14h , @pavelgj :  Why is this closed?  Shouldn't this be merged, or at least fixed in some fashion?  The README refers to a date in the past ( Wednesday, March 23, 2022 ).  The link to the form for the user study ALSO refers to that date.  If the study is still active, then suggesting to update the README, as well as the google form.

**Comment by pavelgj** [comment]
Sorry, closed accidentally.

**Review by cabljac — APPROVED** [review]

**Comment by brucearctor** [comment]
@pavelg -- all good!  Thought this was a reasonable fix to help look like extensions keeps things up-to-date.  Will do what I can to help spread the good word, and get people using where appropriate!

**Pull request merged**
