### PR TITLE
commit jest configs for firestore-bigquery-export packages

### PR DESCRIPTION
**Pull request by IanWyszynski**
This fixes https://github.com/firebase/extensions/issues/260

### CODE REVIEW

**Comment by laurenzlong** [comment]
Thanks for the PR! This is failing the check for prettier, can you run `npm run format` to fix?

**Comment by laurenzlong** [comment]
@firebase/invertase Please review the jest config to ensure it's consistent with the rest of the repo. Thanks!

**Comment by russellwheatley** [comment]
@laurenzlong the `jest.config.js` file uses the same properties as the extensions' packages. Might be worth noting the tests are in a `test` directory compared to the repo using `__tests__`. The test files themselves use `*.spec.ts` whilst the repo uses `*test.ts`.

**Comment by russellwheatley** [comment]
Sorry to be a pedant, but the `__test__` directory is missing an 's', the other packages have a `__tests__` directory.

**Comment by IanWyszynski** [comment]
> Changing to `__tests__` directory, and the `testMatch` property to suit in `jest.config`. Should be good to go once those changes are made

Done! Thanks for catching that.

**Comment by russellwheatley** [comment]
I consent

**Pull request merged**
