### PR TITLE
chore(*): add new cloud functions locations

### LINKED ISSUE #387: Add support for new locations
CF3 has added the following regions recently. Let's add these locations to each extension as well: 
  - `us-west2`
  - `us-west3`
  - `us-west4`
  - `europe-west6`
  - `asia-northeast2`
  - `northamerica-northeast1`
  - `southamerica-east1`
  - `australia-southeast1`

### PR DESCRIPTION
**Pull request by rosariopfernandes**
This should resolve #387 

cc: @Ehesp

### CODE REVIEW

**Comment by karayu** [comment]
Quick note: 3 more locations coming late this week, might make sense to add those in before merging

**Comment by dackers86** [comment]
Additional locations tested, please see the full list below...

- [x] Los Angeles (us-west2)
- [x] Salt Lake City (us-west3)
- [x] Las Vegas (us-west4)
- [x] Zurich (europe-west6)
- [] Osaka (asia-northeast2)
- [] Seoul (asia-northeast3)
- [x] Mumbai (asia-south1)
- [] Jakarta (asia-southeast2)
- [x] Montreal (northamerica-northeast1)
- [x] Sao Paulo (southamerica-east1)
- [x] Sydney (australia-southeast1)

**Comment by i14h** [comment]
We need to add additional details around tiers and pricing. Also for @kevinthecheung to look at the copy after we add the details.

**Comment by karayu** [comment]
Actually, can we link out to https://firebase.google.com/docs/functions/locations? It will have the pricing tiers detail shortly.

**Comment by rosariopfernandes** [comment]
@karayu Seems like that link is already on the `location` param description:

https://github.com/firebase/extensions/blob/5759cbc95f9c4ad59b1133a1a04a9ad28129cffa/firestore-translate-text/extension.yaml#L63-L69

Should we maybe change that sentence to something like:

```
For more information about locations and their pricing tiers, refer to the [location selection 
 guide](https://firebase.google.com/docs/functions/locations).
```
?

**Review by kevinthecheung — APPROVED** [review]

**Pull request merged**
