### PR TITLE
June 23, 2022 Release

### PR DESCRIPTION
**Pull request by huangjeff5**

### CODE REVIEW

**Comment by dreinon** [comment]
Hi! I understand this release is expected to be merged soon, right?

**Comment by huangjeff5** [comment]
> Hi! I understand this release is expected to be merged soon, right?

Hi dreinon, thanks for reaching out. Yes this release should be merged and published sometime between Tuesday and Thursday next week. Will report back when it's ready.

**Review by dackers86 — APPROVED** [review]

**Comment by carlosflorencio** [comment]
Thanks for the release, after updating the extension via Firebase UI, GCloud Functions complains about the last deployment has failed. On the Firebase UI everything seems to have worked fine:

image

image

image

Happened to anyone else? I'm assuming the functions are still running but with the previous version.

**Comment by huangjeff5** [comment]
Hey Carlos good catch. It appears there's a bug on Cloud build such that we need to manually rebuild the extensions before publishing. Just did this and bumped the version. Could you try again?

**Comment by carlosflorencio** [comment]
Works fine now @huangjeff5 👍 .

**Pull request merged**
