### PR TITLE
chore(firestore-bigquery-change-tracker): increment version to 1.1.12

### PR DESCRIPTION
**Pull request by dackers86**
fixes https://github.com/firebase/extensions/issues/621

### CODE REVIEW

**Comment by dackers86** [comment]
@jhuleatt This is now ready for bumping the version

**Review by Salakar — APPROVED** [review]

**Comment by dackers86** [comment]
Would it be worth also be worth bumping the `firestore-bigquery-export` dependency to match this change, 

eg. `"@firebaseextensions/firestore-bigquery-change-tracker": "^1.1.12",`

Or should we treat this as a separate PR?

**Comment by jhuleatt** [comment]
Let's bump the `firestore-bigquery-export` dependency that separately, since the `^` in `^1.1.10` means it will pick up `1.1.12` automatically for all new installs

**Review by jhuleatt — APPROVED** [review]

**Comment by jhuleatt** [comment]
Sorry I didn't notice this earlier - I'm a bit nervous about releasing an update on Friday, just in case we somehow really break things. Let's wait to release this until Monday

**Comment by jhuleatt** [comment]
`@firebaseextensions/firestore-bigquery-change-tracker` version `1.1.12` has been published

**Pull request merged**
