### PR TITLE
docs(firestore-bigquery-export): clarify meaning of "exclude old data"

### PR DESCRIPTION
**Pull request by gregfenton**
The original description is generically worded.  This additional specificity should make it clear to Firestore users what is meant by "old data".

### CODE REVIEW

**Comment by cabljac** [comment]
Hi there! thanks for contributing!

**Comment by pr-Mais** [comment]
Hi @gregfenton, the README is still missing, could you please `npm run generate-readme` and push the generated file?

**Comment by gregfenton** [comment]
Is there a document describing how to make docs PRs in a "clean way" ? I'd prefer to get it right on the first pass, and not bother busy people like y'all 😊

**Comment by pr-Mais** [comment]
Thanks @gregfenton! currently there isn't, but having one would definitely is better for community contributors.

**Comment by gregfenton** [comment]
I'd be cool with nothing more than a bullet-list:

1. clone repo
1. npm install
1. edit files as you see fit
1. npm run generate-readme
1. commit & push (or PR)

**Comment by cabljac** [comment]
Tests are failing, and I think it's because they need an environment variable from the repo secrets. I'll reopen this (and keep your commits etc) from a branch

**Comment by cabljac** [comment]
closing in favour of https://github.com/firebase/extensions/pull/2124

**Pull request closed without merging**
