### PR TITLE
fix(firestore-bigquery-export): Remove broken partition table check

### PR DESCRIPTION
**Pull request by adamkeys**
This commit removes a misplaced guard found in the isTablePartitioned method of the Partitioning class. The removed conditional was erroneously checking the truthfulness of a result of a method which returns a promise, thereby always evaluating to being true. Additionally, the removed logging operation is unrelated to the purpose of the method. This errant code likely ended up here as a result of a failed merge. This addresses an issue where firestore-bigquery-export needlessly fills the logs with errors about not being able to partition an existing table even when partitioning is disabled.

The log message called upon by the removed guard is also removed as it is no longer used. It may want to be reintroduced as part of the partitioning table creation phase in a future update, but that is outside of the scope of this update.

Additional discussion found in #1368

### CODE REVIEW

**Comment by cabljac** [comment]
Hi there @adamkeys , thanks for your contribution! Could you sign the CLA, so I can run some CI checks?

**Comment by adamkeys** [comment]
All set @cabljac

**Comment by dackers86** [comment]
Hi @adamkeys 

Are we certain this not needed. Table is optional in the partition constructor.

Is this guard not necessary to ensure that we do not attempt to partition an existing table?

**Comment by cabljac** [comment]
I think (if it is necessary and stays) it also requires an `await` in the check, as discussed in the linked issue

**Pull request closed without merging**
