### PR TITLE
feat(firestore-counter): Add Node.js Admin SDK Implementation

### PR DESCRIPTION
**Pull request by Mansehej**
The firestore distributed counter SDK does not exist for backend services like Node.js (#28).
This PR aims to solve that by converting the web client Typescript implementation into Node.js.

### CODE REVIEW

**Comment by Mansehej** [comment]
@googlebot I fixed it.

**Comment by Mansehej** [comment]
Can someone please take a look into this? @Salakar @dackers86 @jhuleatt

**Comment by Mansehej** [comment]
Thanks for looking into this, @Salakar . Does this require any changes on my part? Possibly running prettier on all files?

**Review by dackers86 — APPROVED** [review]

**Comment by dackers86** [comment]
@googlebot I consent.

**Comment by dackers86** [comment]
Thanks @Mansehej 

Formatting checks ran and Google consent added. 

This should be good to go pending any other reviews.

**Comment by huangjeff5** [comment]
@kevinthecheung Could you take a look at the doc changes in this PR? Thanks!

**Review by kevinthecheung — APPROVED** [review]

**Pull request merged**
