### PR TITLE
feat(firestore-bigquery-export): support collectionGroup queries

### LINKED ISSUE #17: firestore-bigquery-export fs-bq-import-collection doesn't allow {widecard} path
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Configuration values (redact info where appropriate):
  - fs-bq-import-collection

#### Steps to reproduce:

1) Clone this repo.
2) Go to extensions/firestore-bigquery-export/scripts/import and install dependencies (npm install)
3) Execute `npm run import`
4) Pass the ${PROJECT_ID}
5) Try pass a widecard path as described on docs, like `chats/{chatid}/posts`
6) Get an error: `>> The collection path must only contain letters or spaces`
##### Expected result
Allow widecard paths to import.
##### Actual result
Get an error: `>> The collection path must only contain letters or spaces`

### PR DESCRIPTION
**Pull request by russellwheatley**
- Created a new parameter which allows the user to decide if the imported Firestore documents are queried via a `collection` query or a `collectionGroup` query.
- Doesn't fully solve #17 as wildcards aren't allowed in Firestore queries. 
- Updated recently merged `non-interactive` option to also accept `--query-collection-group` parameter. This feature can now be used interactively or non-interactively.

## Testing

Tested the import of a collection with 30 documents using a `collection` query:
Screenshot 2020-06-29 at 12 06 22

Tested the import of a sub-collection with 2 documents using a `collectionGroup` query:
Screenshot 2020-06-29 at 12 06 32

I've also added the `collectionGroup` query as an argument to be used during `--non-interactive` mode: https://github.com/firebase/extensions/pull/354/files#diff-2f74e55e61e11ab08c67d590ea86116bR82

Screenshot 2020-07-14 at 10 52 13

### CODE REVIEW

**Comment by Ehesp** [comment]
@googlebot I consent.

**Comment by Ehesp** [comment]
@russellwheatley I've just pushed a commit to make this optional as discussed.

**Comment by russellwheatley** [comment]
LGTM

**Comment by russellwheatley** [comment]
Tested the import of a collection with 30 documents using a `collection` query:
Screenshot 2020-06-29 at 12 06 22

Tested the import of a sub-collection with 2 documents using a `collectionGroup` query:
Screenshot 2020-06-29 at 12 06 32

**Comment by russellwheatley** [comment]
I've updated this PR in light of the `--non-interactive` import PR merging into `next` (https://github.com/firebase/extensions/pull/328)

I've added the `collectionGroup` query as an argument to be used during `--non-interactive` mode: https://github.com/firebase/extensions/pull/354/files#diff-2f74e55e61e11ab08c67d590ea86116bR82

**Comment by nwparker** [comment]
Wanted to mention that I was able to use this branch locally with success for importing by collectionGroup. Thank you!

Hope it can eventually be merged to help others more easily

**Review by jhuleatt — APPROVED** [review]

**Pull request merged**
