### PR TITLE
release: March 2024

### PR DESCRIPTION
**Pull request by pr-Mais**

### CODE REVIEW

**Review by rrousselGit — APPROVED** [review]

**Comment by rrousselGit** [comment]
Frieren adapting to the modern world and programming would be quite the sight

**Comment by pietermarsman** [comment]
Thanks for all the work! 

I can't wait for the next release of firestore-bigquery-export! :smile: What is the plan for releasing this?

**Comment by pr-Mais** [comment]
@jauntybrain the changelog for bigquery export is not well expressive, also it's' missing the last fix with retryConfig, can you add more details on the changes.

**Comment by jauntybrain** [comment]
@pr-Mais added new changelog PR here: #1998

**Comment by pietermarsman** [comment]
:tada:

**Comment by pr-Mais** [comment]
@pietermarsman let us know if you face any issue in the new release, thanks for your patience!

**Pull request merged**
