### PR TITLE
fix(firestore-bigquery-export): add package & update exports

### LINKED ISSUE #196: Cannot read property 'fields' is undefined when running fs-bq-schema-views
Updated all schema views without issue, but when checking data noticed on field was null, reviewed and noticed the mistake in the json. Corrected and attempted to run the script again. It will do the changelog fine, but after it finishes and moves to do latest it displays "Cannot read property 'fields' is undefined ". Also after the failure to check ran again using the previous json that worked fine before and get the same results with the changelog being correct and it failing on the latest.

### LINKED ISSUE #250: Generate Schema - cannot find '@firebaseextensions/firestore-bigquery-change-tracker'
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **fs-bq-schema-views** 
- Extension version: **n/a**
- Configuration values (redact info where appropriate):
  - **PROJECT_ID: myproject**
  - **COLLECTION PATH: mycollection**
  - **DATASET ID: dataset**
  - **TABLE_PREFIX: table**

### [REQUIRED] Step 3: Describe the problem
When running `npx @firebaseextensions/fs-bq-schema-views \ ...` got an error `cannot find '@firebaseextensions/firestore-bigquery-change-tracker'` with no schema or views created. Tried several times and various prefix but it didn't work.
#### Steps to reproduce:
Follow the steps described in the guide [here](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)
What happened? How can we make the problem occur?
The package does not seem to exist.
error

##### Expected result
Schema and views created
##### Actual result
Error and nothing was created.

### PR DESCRIPTION
**Pull request by russellwheatley**
fixes #250 
- The latest commit for the `gen-schema-view` uses the `firestore-bigquery-change-tracker` package  script which is not specified in the `package.json`.

fixes #196
- The `RawChangelogViewSchema ` was not exported out of the `firestore-bigquery-change-tracker` package. This caused the `fields` property to be `undefined` at this [point](https://github.com/firebase/extensions/blob/d4c56a510094b19c0809d24f335b6c39ecc104de/firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts#L193) in the code.

Here's a screenshot of the `gen-schema-view` script working again:
Screenshot 2020-04-09 at 12 55 13

Please note that the `gen-schema-view` package will still not work until this PR has been merged and the `firestore-bigquery-change-tracker` & `gen-schema-view` packages have been published again.

### CODE REVIEW

**Comment by newadays** [comment]
Thanks @russellwheatley Do we have update on merging the PR?

**Comment by stari4ek** [comment]
And since new dependency `DEVSETUP.md` should be also updated

**Comment by kiendt07** [comment]
Pls merge this PR soon 🙇‍♂️

**Comment by laurenzlong** [comment]
firestore-bigquery-change-tracker and gen-schema-view have both been updated on NPM.

**Comment by sommes54** [comment]
`{
        "fields": [
          {
            "name": "main",
            "type": "string"
          },
          {
            "name": "medium",
            "type": "string"
          },
          {
            "name": "small",
            "type": "string"
          },
          {
            "name": "thumbnail",
            "type": "string"
          }
        ],
        "name": "mainImage",
        "type": "map"
      },`

I am not sure if this is caused by the change but map type are no longer working. @russellwheatley any thoughts?

**Comment by laurenzlong** [comment]
If your Firestore document is structured like: 
```Map => {
"mainImage": {
"main": "url1",
"small": "url2",
"medium": "url3",
"thumbnail": "url4"
}
}
```

Can you ensure your schema file is:

```
{
  "fields": [
    {
      "fields": [
 { "name": "main", "type": "string" }, { "name": "medium", "type": "string" }, { "name": "small", "type": "string" }, { "name": "thumbnail", "type": "string" }
      ],
      "name": "mainImage",
      "type": "map"
    }
  ]
}
```

**Comment by newadays** [comment]
Thank you @laurenzlong. I tried to run with the format you shared with but it gave a different error.

`{"code":400,"errors":[{"message":"Provided Schema does not match Table PROJECT_ID:firestore_export.allProducts_schema_schema_changelog. Cannot add fields (field: mainImage_main)","domain":"global","reason":
"invalid"}],"message":"Provided Schema does not match Table PROJECT_ID:firestore_export.allProducts_schema_schema_changelog. Cannot add fields (field: mainImage_main)"}
Provided Schema does not match Table PROJECT_ID:firestore_export.allProducts_schema_schema_changelog. Cannot add fields (field: mainImage_main)`

It seems the script adds "_" whereas the schema generated from the Firestore export has the "." map notations e.g. mainImage.main is the correct field name where as "mainImage_main" does not exist. Is there a way to have the name generated by the firestore export.

**Comment by laurenzlong** [comment]
Hi @newadays could you please file a new Github issue for this?

**Comment by russellwheatley** [comment]
I believe the error has been fixed now as I've tried running the `npx @firebaseextensions/fs-bq-schema-views` with @laurenzlong's  above mentioned schema and data structure and I was able to successfully create the table. Here's the console logs showing the data being accessed using dot notation whilst correctly using the underscore for the column names:
Screenshot 2020-04-20 at 12 54 45

Here is the data in the resulting view table:
Screenshot 2020-04-20 at 12 57 56

Could you try running `npx @firebaseextensions/fs-bq-schema-views` and let me know if you still get the same error, please @newadays?

**Pull request merged**
