### PR TITLE
fix(storage-resize-images): fix posix issue on windows

### PR DESCRIPTION
**Pull request by cabljac**
This will fix https://github.com/firebase/extensions/issues/1732

### CODE REVIEW

**Review by pr-Mais — APPROVED** [review]
LGTM

**Comment by TheKents0209** [comment]
Still having this problem with v0.2.1 "Image path 'C:\\images' is not supported, these are the supported absolute paths: /images"

**Comment by TheKents0209** [comment]
> Still having this problem with v0.2.1 "Image path 'C:\images' is not supported, these are the supported absolute paths: /images"

If anyone else encounters this problem, I fixed the issue by removing `INCLUDE_PATH_LIST=images/` completely from extensions' .env.

For some reason resized images still go into {bucket}/images

**Comment by cabljac** [comment]
I will open a new issue to track on Monday, thanks!

**Pull request merged**
